---
swagger: "2.0"
info:
  description: "A Simple IP Address API"
  version: "v1"
  title: "api.ipify.org"
host: "localhost:8080"
basePath: "/"
schemes:
- "https"
paths:
  /getcity:
    get:
      summary: "Find city by name"
      description: "Returns the dataframe of the city"
      operationId: "get_cityby_name"
      produces:
      - "application/json"
      parameters:
      - name: "cityName"
        in: "query"
        description: "parameter city"
        required: false
        type: "string"
        default: "Madrid"
      responses:
        "200":
          description: "success"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/HotelArray"
        "400":
          description: "Invalid name supplied"
        "500":
          description: "City not found"
      x-swagger-router-controller: "swagger_server.controllers.default_controller"
definitions:
  HotelArray:
    type: "array"
    items:
      $ref: "#/definitions/HotelArrayJson"
  HotelArrayJson:
    type: "object"
    properties:
      address.locality:
        type: "string"
        example: "Murcia"
      address.postalCode:
        type: "string"
        example: "30820"
      category:
        type: "string"
      cityname:
        type: "string"
        example: "Murcia"
      date_update:
        type: "integer"
      distance:
        type: "integer"
      distanceInTime:
        type: "string"
      guestReviews.rating:
        type: "number"
      id:
        type: "integer"
      locations:
        type: "string"
      name_x:
        type: "string"
      name_y:
        type: "string"
      neighbourhood:
        type: "string"
      ratePlan.price.exactCurrent:
        type: "number"
      starRating:
        type: "number"
      supplierHotelId:
        type: "integer"
      type_transports:
        type: "string"
